# Generated by Django 5.0.6 on 2024-11-05 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_executor_alter_application_executor'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='applications/%Y/%m/%d/'),
        ),
    ]
