# Generated by Django 5.0.6 on 2024-11-06 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_application_pdf_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField(verbose_name='Номер шага')),
                ('title', models.CharField(max_length=200, verbose_name='Название шага')),
                ('description', models.TextField(verbose_name='Описание шага')),
            ],
        ),
        migrations.AlterField(
            model_name='application',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
